/**
 * Core domain types for Chatpack.
 *
 * These types describe the durable chat domain from MVP §8: conversations
 * (1:1 and group), participants, and messages. Users are referenced **by id
 * only** - Chatpack never owns a users table.
 *
 * @module
 */

/**
 * Arbitrary JSON-serializable metadata attached to conversations and messages.
 *
 * This is the deliberate escape hatch (MVP §3, §8): developers can store
 * things like `{ attachmentUrl: "..." }` or AI-specific context without
 * Chatpack needing first-class features for them.
 */
export type Metadata = Record<string, unknown>;

/**
 * The role of a message sender.
 *
 * Defaults to `"user"`. `"assistant"` and `"system"` exist purely as the AI
 * escape hatch (MVP §5, §8) - core never behaves differently based on role.
 */
export type MessageRole = "user" | "assistant" | "system";

/**
 * Whether a conversation is a 1:1 DM or a multi-participant group
 * (`docs/decisions/0017`).
 *
 * Deliberately a discriminator on one interface rather than a
 * `DirectConversation | GroupConversation` union: a union would be more precise
 * but would break every existing `conversation.pairKey` read at the type level
 * for no runtime benefit.
 */
export type ConversationType = "direct" | "group";

/**
 * Whether a conversation can be found by people who are not in it
 * (`docs/decisions/0020`).
 *
 * `"public"` is what makes a group a **channel**: it appears in
 * `listPublicConversations` and can be self-joined. There is deliberately no
 * `"channel"` {@link ConversationType} - a channel is a group with this field
 * flipped, so every group feature (roles, invites, rename, membership) applies
 * to it unchanged (ADR 0020 §1).
 *
 * Discovery only: `"public"` does **not** let non-members read messages.
 * `canRead` stays a membership test, so joining is still the way in.
 */
export type ChannelVisibility = "private" | "public";

/**
 * How a non-member gets into a public channel once they have found it
 * (`docs/decisions/0020` §3).
 *
 * `"open"` admits them immediately; `"approval"` creates a pending
 * {@link JoinRequest} for an admin to resolve, reusing the ADR 0019 queue.
 * Defaults to `"approval"` - between "a stranger is in the room" and "a
 * stranger is in a queue", only one is recoverable.
 *
 * Inert while {@link ChannelVisibility} is `"private"`: strangers cannot
 * discover the conversation, so setting this is arming, not opening.
 */
export type ChannelJoinPolicy = "open" | "approval";

/**
 * A participant's authority within a **group** conversation
 * (`docs/decisions/0017`).
 *
 * Unrelated to {@link MessageRole} - that describes who authored a message
 * (`user`/`assistant`/`system`), this describes what a member may do. Direct
 * conversations always report `"member"`: a DM has no hierarchy, and implying
 * one would suggest it can be administered.
 */
export type ParticipantRole = "admin" | "member";

/**
 * A conversation: either a 1:1 DM between exactly two users, or a group of up
 * to `MAX_GROUP_PARTICIPANTS` (`docs/decisions/0017`).
 *
 * `type` discriminates the two. Everything else about the domain - `seq`,
 * read-state, unread counts, reactions, replies - is per-conversation or
 * per-participant and counts to N, not to two.
 */
export interface Conversation {
  /** Unique conversation id (generated by the storage adapter). */
  id: string;
  /** Whether this is a 1:1 DM or a group (`docs/decisions/0017`). */
  type: ConversationType;
  /**
   * Deterministic key for the pair of participants, computed by core as the
   * sorted user ids joined with `":"` (e.g. `"alice:bob"`). Guarantees a
   * single conversation per user pair - see `docs/decisions/0002-pair-key.md`.
   *
   * **`null` for groups.** Two groups with identical membership are two
   * different groups (a "standup" and a "lunch" group with the same five
   * people are not the same conversation), so groups are created, never
   * found-or-created.
   */
  pairKey: string | null;
  /**
   * Group title, or `null` for a direct conversation. Trimmed, non-empty when
   * present, at most {@link MAX_CONVERSATION_NAME_LENGTH} characters.
   *
   * A group may legitimately have no name - clients render a participant list
   * instead, the way Slack and iMessage both do.
   */
  name: string | null;
  /**
   * Whether people who are not in this conversation can find it
   * (`docs/decisions/0020`). Always `"private"` for a direct conversation, and
   * for any group that has not opted in.
   *
   * A group with `"public"` is what the docs call a **channel**. Setting it
   * requires a storage adapter with the `channels` capability - core answers
   * `CHANNELS_UNSUPPORTED` rather than accepting a value it cannot persist.
   */
  visibility: ChannelVisibility;
  /**
   * How a non-member joins, once they have discovered this conversation
   * (`docs/decisions/0020` §3). Defaults to `"approval"`.
   *
   * Only consulted for a self-service join of a `"public"` conversation. A
   * join that presents an **invite code** follows that invite's
   * `requiresApproval` instead: the policy lives on whatever the joiner
   * presents.
   */
  joinPolicy: ChannelJoinPolicy;
  /** Creation timestamp. */
  createdAt: Date;
  /** Developer-defined metadata (escape hatch). */
  metadata: Metadata;
  /**
   * The participants of this conversation. Exactly two for `type: "direct"`;
   * one or more for `type: "group"` (a group starts with just its creator).
   */
  participants: Participant[];
}

/**
 * A conversation as returned by the API: the storage shape plus the viewer's
 * `unreadCount` (messages newer than their read-state, excluding their own).
 *
 * `Conversation` itself stays viewer-independent - adapters and permission
 * hooks never see this field; core computes it per request via
 * `StorageAdapter.countUnread`.
 */
export type ConversationWithUnread = Conversation & { unreadCount: number };

/**
 * A user's membership in a conversation, including their durable read-state.
 */
export interface Participant {
  /** The conversation this participation belongs to. */
  conversationId: string;
  /** The developer's user id. Chatpack never resolves or stores user records. */
  userId: string;
  /**
   * What this member may do in a group (`docs/decisions/0017`). Admins add and
   * remove members, change roles, and rename the group; members send and read.
   * Always `"member"` in a direct conversation.
   */
  role: ParticipantRole;
  /** When the user joined (for 1:1, conversation creation time). */
  joinedAt: Date;
  /**
   * Durable read-state: the id of the last message this user has read, or
   * `null` if they have read nothing. Survives reconnects and answers
   * "have they seen up to X?" (MVP §2).
   */
  lastReadMessageId: string | null;
}

/**
 * A text message inside a conversation.
 */
export interface Message {
  /** Unique message id (generated by the storage adapter). */
  id: string;
  /** The conversation this message belongs to. */
  conversationId: string;
  /** The sender's user id. */
  senderId: string;
  /** The message text. Empty for soft-deleted messages. */
  body: string;
  /** Sender role. Defaults to `"user"`; AI escape hatch only. */
  role: MessageRole;
  /**
   * Monotonic sort key (MVP §8): assigned by storage as a strictly increasing
   * integer per conversation, so clients can reconcile SSE events against
   * fetched history deterministically even when `createdAt` collides.
   */
  seq: number;
  /** Creation timestamp. */
  createdAt: Date;
  /** Set when the message body was last edited; `null` if never edited. */
  editedAt: Date | null;
  /**
   * Soft-delete timestamp (MVP §2). Deleted messages remain in history with
   * an empty body so clients can render a tombstone; `null` if not deleted.
   */
  deletedAt: Date | null;
  /**
   * The message this one quote-replies to, or `null` for a normal message
   * (`docs/decisions/0013`). Always in the same conversation, always one hop -
   * a reply to a reply is still flat, and v0 has no threads. Immutable: edits
   * only ever change the body.
   */
  replyToMessageId: string | null;
  /** Developer-defined metadata (escape hatch). */
  metadata: Metadata;
}

/**
 * One user's reaction to one message (`docs/decisions/0013`).
 *
 * Durable, but not a message: reactions have no `seq`, never light the unread
 * badge, and never reorder the conversation list.
 */
export interface Reaction {
  /** The message being reacted to. */
  messageId: string;
  /** The reacting user's id. */
  userId: string;
  /**
   * The reaction key: any non-empty string up to 32 characters, trimmed.
   * Usually an emoji, but `":shipit:"` or a custom emoji id are equally
   * valid - Chatpack stays unopinionated (ADR 0013 §3).
   */
  emoji: string;
  /** When the reaction was added. */
  createdAt: Date;
}

/**
 * Reactions of one kind on one message, aggregated by core for the API.
 *
 * Viewer-independent: v0 is 1:1, so `userIds` holds at most two entries and a
 * client can tell "did I react?" without a viewer-relative field.
 */
export interface ReactionSummary {
  /** The reaction key. */
  emoji: string;
  /** How many users reacted with it. 1 or 2 in v0. */
  count: number;
  /** Who reacted, earliest first. */
  userIds: string[];
}

/**
 * A read-only preview of a quote-replied message, resolved per request by
 * core - never stored (`docs/decisions/0013`).
 *
 * Hydrating rather than denormalizing means the preview cannot go stale when
 * the parent is edited, and a client can render the quote bar even when the
 * parent is far outside the loaded page.
 */
export interface MessageReference {
  /** The parent message's id. */
  id: string;
  /** Who sent the parent. */
  senderId: string;
  /**
   * The first 140 characters of the parent body, suffixed with `"…"` when
   * truncated. Empty string when the parent is a tombstone.
   */
  excerpt: string;
  /** `true` when the parent has been soft-deleted. */
  deleted: boolean;
}

/**
 * A shareable link that grants membership of one group
 * (`docs/decisions/0019`).
 *
 * The `code` is both the identity and the secret: possession is the
 * permission, the way a document share link works. It is stored in plaintext
 * rather than hashed so an admin can re-display a link they already handed
 * out - see ADR 0019 §3 for the tradeoff and what bounds it (revocation,
 * expiry, use caps).
 */
export interface ConversationInvite {
  /**
   * The invite secret, 32 random bytes as base64url. Generated by core, not by
   * the adapter: an id needs to be unique, a token needs to be unguessable,
   * and entropy is not a storage detail (ADR 0019 §3).
   */
  code: string;
  /** The group this invite admits people to. */
  conversationId: string;
  /** Who minted the invite. */
  createdBy: string;
  /** When the invite was minted. */
  createdAt: Date;
  /** When the invite stops working, or `null` to never expire. */
  expiresAt: Date | null;
  /** How many times it may be redeemed, or `null` for unlimited. */
  maxUses: number | null;
  /** How many times it has been redeemed so far. */
  uses: number;
  /**
   * When `true`, redeeming creates a pending {@link JoinRequest} instead of
   * joining outright. Per-invite rather than per-group so one group can hand
   * out an open link to the team and a gated link to the public (ADR 0019 §4).
   */
  requiresApproval: boolean;
  /** Developer-defined metadata (escape hatch). */
  metadata: Metadata;
}

/**
 * What a link holder may see before joining (`docs/decisions/0019` §10).
 *
 * Deliberately not a {@link Conversation}: returning one would hand every
 * member's user id to anyone holding a link, whether or not they ever join. A
 * count answers "is this the right group?" without naming anyone.
 */
export interface InvitePreview {
  /** The group the invite admits you to. */
  conversationId: string;
  /** The group's name, or `null` if it has none. */
  name: string | null;
  /** How many people are currently in the group. No ids (see above). */
  participantCount: number;
  /** Whether accepting joins immediately or creates a pending request. */
  requiresApproval: boolean;
  /** Who minted the invite. */
  invitedBy: string;
  /** `true` when the caller is already a participant, so accepting is a no-op. */
  alreadyParticipant: boolean;
}

/** Whether a join request is still waiting, or has been decided. */
export type JoinRequestStatus = "pending" | "approved" | "denied";

/**
 * A user asking to join a group, awaiting an admin decision
 * (`docs/decisions/0019`).
 *
 * Reachable two ways: directly via `requestToJoin` for a group the user knows
 * the id of, or by redeeming an invite whose `requiresApproval` is `true`.
 * Either way one admin resolution path decides it.
 *
 * At most one row per `(conversationId, userId)`: a fresh request from a
 * previously denied user replaces the old row rather than accumulating.
 * Denial is therefore not a block - blocking is a moderation feature with its
 * own list, and it is out of scope (ADR 0019 §5).
 */
export interface JoinRequest {
  /** Unique request id (generated by the storage adapter). */
  id: string;
  /** The group being asked to join. */
  conversationId: string;
  /** Who is asking. */
  userId: string;
  /** Whether it is still waiting, or how it was decided. */
  status: JoinRequestStatus;
  /**
   * An optional note from the requester ("I'm on the design team"), trimmed,
   * at most {@link MAX_JOIN_REQUEST_MESSAGE_LENGTH} characters. `null` when
   * none was given.
   */
  message: string | null;
  /**
   * The invite that produced this request, or `null` when the user asked
   * directly. Kept so an admin can tell "came from the public link" from
   * "found us and asked".
   */
  inviteCode: string | null;
  /** When the request was made. */
  createdAt: Date;
  /** When it was approved or denied; `null` while pending. */
  resolvedAt: Date | null;
  /** Which admin decided it; `null` while pending. */
  resolvedBy: string | null;
  /** Developer-defined metadata (escape hatch). */
  metadata: Metadata;
}

/**
 * One row in the public channel directory (`docs/decisions/0020` §2).
 *
 * The same reasoning as {@link InvitePreview}, applied to a wider audience:
 * the directory is readable by every authenticated user, so it must never
 * name a member. A count answers "is this worth joining?"; ids would leak the
 * membership of every public channel to everyone.
 *
 * Core narrows a full {@link Conversation} down to this - the adapter returns
 * ordinary rows, and the field list here is what survives.
 */
export interface ChannelPreview {
  /** The channel you would be joining. */
  conversationId: string;
  /** The channel's name, or `null` if it has none. */
  name: string | null;
  /** How many people are currently in it. No ids (see above). */
  participantCount: number;
  /** Whether joining admits you immediately or opens a {@link JoinRequest}. */
  joinPolicy: ChannelJoinPolicy;
  /** When the channel was created. */
  createdAt: Date;
  /** Developer-defined metadata (escape hatch) - the place for a description. */
  metadata: Metadata;
  /** `true` when the caller is already in, so joining would be a no-op. */
  alreadyParticipant: boolean;
  /**
   * `true` when the caller already has a pending {@link JoinRequest} here, so
   * the honest button label is "requested" rather than "join".
   */
  requestPending: boolean;
}

/**
 * A message as returned by the API: the storage shape plus the two
 * per-request decorations from ADR 0013.
 *
 * `Message` itself stays the storage shape - adapters and permission hooks
 * never see these fields; core computes them via
 * `StorageAdapter.getMessagesByIds` and
 * `StorageAdapter.listReactionsByMessageIds`, batched one call per page.
 */
export type MessageWithDetails = Message & {
  /**
   * Preview of the quoted parent, or `null` when this is not a reply (or the
   * parent row no longer exists at all - soft-deleted parents still resolve,
   * with `deleted: true`).
   */
  replyTo: MessageReference | null;
  /** All reactions on this message, grouped by emoji. Empty when there are none. */
  reactions: ReactionSummary[];
};
