/**
 * Core domain types for Chatpack.
 *
 * These types describe the durable chat domain from MVP §8: 1:1 conversations,
 * participants, and messages. Users are referenced **by id only** - Chatpack
 * never owns a users table.
 *
 * @module
 */

/**
 * Arbitrary JSON-serializable metadata attached to conversations and messages.
 *
 * This is the deliberate escape hatch (MVP §3, §8): developers can store
 * things like `{ attachmentUrl: "..." }` or AI-specific context without
 * Chatpack needing first-class features for them.
 */
export type Metadata = Record<string, unknown>;

/**
 * The role of a message sender.
 *
 * Defaults to `"user"`. `"assistant"` and `"system"` exist purely as the AI
 * escape hatch (MVP §5, §8) - core never behaves differently based on role.
 */
export type MessageRole = "user" | "assistant" | "system";

/**
 * A 1:1 (direct) conversation between exactly two users.
 *
 * v0 has no `type` field - every conversation is direct (MVP §8). A `type`
 * column can be added later when groups land without breaking this shape.
 */
export interface Conversation {
  /** Unique conversation id (generated by the storage adapter). */
  id: string;
  /**
   * Deterministic key for the pair of participants, computed by core as the
   * sorted user ids joined with `":"` (e.g. `"alice:bob"`). Guarantees a
   * single conversation per user pair - see `docs/decisions/0002-pair-key.md`.
   */
  pairKey: string;
  /** Creation timestamp. */
  createdAt: Date;
  /** Developer-defined metadata (escape hatch). */
  metadata: Metadata;
  /** The two participants of this conversation. Always exactly two entries. */
  participants: Participant[];
}

/**
 * A conversation as returned by the API: the storage shape plus the viewer's
 * `unreadCount` (messages newer than their read-state, excluding their own).
 *
 * `Conversation` itself stays viewer-independent - adapters and permission
 * hooks never see this field; core computes it per request via
 * `StorageAdapter.countUnread`.
 */
export type ConversationWithUnread = Conversation & { unreadCount: number };

/**
 * A user's membership in a conversation, including their durable read-state.
 */
export interface Participant {
  /** The conversation this participation belongs to. */
  conversationId: string;
  /** The developer's user id. Chatpack never resolves or stores user records. */
  userId: string;
  /** When the user joined (for 1:1, conversation creation time). */
  joinedAt: Date;
  /**
   * Durable read-state: the id of the last message this user has read, or
   * `null` if they have read nothing. Survives reconnects and answers
   * "have they seen up to X?" (MVP §2).
   */
  lastReadMessageId: string | null;
}

/**
 * A text message inside a conversation.
 */
export interface Message {
  /** Unique message id (generated by the storage adapter). */
  id: string;
  /** The conversation this message belongs to. */
  conversationId: string;
  /** The sender's user id. */
  senderId: string;
  /** The message text. Empty for soft-deleted messages. */
  body: string;
  /** Sender role. Defaults to `"user"`; AI escape hatch only. */
  role: MessageRole;
  /**
   * Monotonic sort key (MVP §8): assigned by storage as a strictly increasing
   * integer per conversation, so clients can reconcile SSE events against
   * fetched history deterministically even when `createdAt` collides.
   */
  seq: number;
  /** Creation timestamp. */
  createdAt: Date;
  /** Set when the message body was last edited; `null` if never edited. */
  editedAt: Date | null;
  /**
   * Soft-delete timestamp (MVP §2). Deleted messages remain in history with
   * an empty body so clients can render a tombstone; `null` if not deleted.
   */
  deletedAt: Date | null;
  /**
   * The message this one quote-replies to, or `null` for a normal message
   * (`docs/decisions/0013`). Always in the same conversation, always one hop -
   * a reply to a reply is still flat, and v0 has no threads. Immutable: edits
   * only ever change the body.
   */
  replyToMessageId: string | null;
  /** Developer-defined metadata (escape hatch). */
  metadata: Metadata;
}

/**
 * One user's reaction to one message (`docs/decisions/0013`).
 *
 * Durable, but not a message: reactions have no `seq`, never light the unread
 * badge, and never reorder the conversation list.
 */
export interface Reaction {
  /** The message being reacted to. */
  messageId: string;
  /** The reacting user's id. */
  userId: string;
  /**
   * The reaction key: any non-empty string up to 32 characters, trimmed.
   * Usually an emoji, but `":shipit:"` or a custom emoji id are equally
   * valid - Chatpack stays unopinionated (ADR 0013 §3).
   */
  emoji: string;
  /** When the reaction was added. */
  createdAt: Date;
}

/**
 * Reactions of one kind on one message, aggregated by core for the API.
 *
 * Viewer-independent: v0 is 1:1, so `userIds` holds at most two entries and a
 * client can tell "did I react?" without a viewer-relative field.
 */
export interface ReactionSummary {
  /** The reaction key. */
  emoji: string;
  /** How many users reacted with it. 1 or 2 in v0. */
  count: number;
  /** Who reacted, earliest first. */
  userIds: string[];
}

/**
 * A read-only preview of a quote-replied message, resolved per request by
 * core - never stored (`docs/decisions/0013`).
 *
 * Hydrating rather than denormalizing means the preview cannot go stale when
 * the parent is edited, and a client can render the quote bar even when the
 * parent is far outside the loaded page.
 */
export interface MessageReference {
  /** The parent message's id. */
  id: string;
  /** Who sent the parent. */
  senderId: string;
  /**
   * The first 140 characters of the parent body, suffixed with `"…"` when
   * truncated. Empty string when the parent is a tombstone.
   */
  excerpt: string;
  /** `true` when the parent has been soft-deleted. */
  deleted: boolean;
}

/**
 * A message as returned by the API: the storage shape plus the two
 * per-request decorations from ADR 0013.
 *
 * `Message` itself stays the storage shape - adapters and permission hooks
 * never see these fields; core computes them via
 * `StorageAdapter.getMessagesByIds` and
 * `StorageAdapter.listReactionsByMessageIds`, batched one call per page.
 */
export type MessageWithDetails = Message & {
  /**
   * Preview of the quoted parent, or `null` when this is not a reply (or the
   * parent row no longer exists at all - soft-deleted parents still resolve,
   * with `deleted: true`).
   */
  replyTo: MessageReference | null;
  /** All reactions on this message, grouped by emoji. Empty when there are none. */
  reactions: ReactionSummary[];
};
