/**
 * Core domain types for Chatpack.
 *
 * These types describe the durable chat domain from MVP §8: 1:1 conversations,
 * participants, and messages. Users are referenced **by id only** — Chatpack
 * never owns a users table.
 *
 * @module
 */

/**
 * Arbitrary JSON-serializable metadata attached to conversations and messages.
 *
 * This is the deliberate escape hatch (MVP §3, §8): developers can store
 * things like `{ attachmentUrl: "..." }` or AI-specific context without
 * Chatpack needing first-class features for them.
 */
export type Metadata = Record<string, unknown>;

/**
 * The role of a message sender.
 *
 * Defaults to `"user"`. `"assistant"` and `"system"` exist purely as the AI
 * escape hatch (MVP §5, §8) — core never behaves differently based on role.
 */
export type MessageRole = "user" | "assistant" | "system";

/**
 * A 1:1 (direct) conversation between exactly two users.
 *
 * v0 has no `type` field — every conversation is direct (MVP §8). A `type`
 * column can be added later when groups land without breaking this shape.
 */
export interface Conversation {
  /** Unique conversation id (generated by core). */
  id: string;
  /**
   * Deterministic key for the pair of participants, computed by core as the
   * sorted user ids joined with `":"` (e.g. `"alice:bob"`). Guarantees a
   * single conversation per user pair — see `docs/decisions/0002-pair-key.md`.
   */
  pairKey: string;
  /** Creation timestamp. */
  createdAt: Date;
  /** Developer-defined metadata (escape hatch). */
  metadata: Metadata;
  /** The two participants of this conversation. Always exactly two entries. */
  participants: Participant[];
}

/**
 * A user's membership in a conversation, including their durable read-state.
 */
export interface Participant {
  /** The conversation this participation belongs to. */
  conversationId: string;
  /** The developer's user id. Chatpack never resolves or stores user records. */
  userId: string;
  /** When the user joined (for 1:1, conversation creation time). */
  joinedAt: Date;
  /**
   * Durable read-state: the id of the last message this user has read, or
   * `null` if they have read nothing. Survives reconnects and answers
   * "have they seen up to X?" (MVP §2).
   */
  lastReadMessageId: string | null;
}

/**
 * A text message inside a conversation.
 */
export interface Message {
  /** Unique message id (generated by core). */
  id: string;
  /** The conversation this message belongs to. */
  conversationId: string;
  /** The sender's user id. */
  senderId: string;
  /** The message text. Empty for soft-deleted messages. */
  body: string;
  /** Sender role. Defaults to `"user"`; AI escape hatch only. */
  role: MessageRole;
  /**
   * Monotonic sort key (MVP §8): assigned by storage as a strictly increasing
   * integer per conversation, so clients can reconcile SSE events against
   * fetched history deterministically even when `createdAt` collides.
   */
  seq: number;
  /** Creation timestamp. */
  createdAt: Date;
  /** Set when the message body was last edited; `null` if never edited. */
  editedAt: Date | null;
  /**
   * Soft-delete timestamp (MVP §2). Deleted messages remain in history with
   * an empty body so clients can render a tombstone; `null` if not deleted.
   */
  deletedAt: Date | null;
  /** Developer-defined metadata (escape hatch). */
  metadata: Metadata;
}
